name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Bileto Cronner source code
      uses: actions/checkout@v3

    - name: Validate Composer files
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check code style with PHPStan
      uses: php-actions/phpstan@v2
      with:
        php_version: "8.0"
        php_extensions: calendar

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Run test suite
      uses: php-actions/composer@v6
      with:
        php_version: "8.0"
        php_extensions: calendar
        command: run-script test
